#!/usr/bin/env python3
"""
Gemini Context Hub Sync Script

Merges per-project docs into single context files for Gemini Custom Gems upload.
Solves the 10-file upload limit by consolidating 6 docs/project → 1 file/project.

Usage:
    python3 ~/.claude/scripts/gemini_context_sync.py
    # or via alias: gemini-sync
"""

import os
import sys
from datetime import datetime
from pathlib import Path

# ============================================================
# Configuration
# ============================================================

TARGET_DIR = Path.cwd()  # Output to current working directory

# Project name → absolute path to project root
PROJECTS = {
    "flametree_pick": Path.home() / "LittleTree_Projects/flutter/flametree_pick",
    "flametree_rss_reader": Path.home() / "LittleTree_Projects/flutter/flametree_rss_reader",
    "littletree_ai": Path.home() / "LittleTree_Projects/flutter/littletree_ai",
    "littletree_x": Path.home() / "LittleTree_Projects/flutter/littletree_x",
    "lt_music": Path.home() / "LittleTree_Projects/flutter/lt_music",
    "my-website": Path.home() / "LittleTree_Projects/front-end/my-website",
    "nas-server": Path.home() / "LittleTree_Projects/server/nas-server",
}

# Doc merge order: abstract → concrete, intent → status
DOC_ORDER = [
    "PRODUCT_SOUL.md",
    "ui/UI_SHOWCASE.md",
    "PRODUCT_BEHAVIOR.md",
    "ARCHITECTURE.md",
    "FEATURE_CODE_MAP.md",
    "ROADMAP.md",
]


# ============================================================
# Core Logic
# ============================================================


def read_file(path: Path) -> str | None:
    """Read file content, return None if not exists."""
    if path.is_file():
        return path.read_text(encoding="utf-8").strip()
    return None


def extract_one_liner(soul_content: str) -> str:
    """Extract first meaningful line from PRODUCT_SOUL as project description."""
    for line in soul_content.splitlines():
        line = line.strip()
        # Skip headings, empty lines, separators
        if not line or line.startswith("#") or line.startswith("---") or line.startswith(">"):
            continue
        # Return first content line (truncate if too long)
        return line[:120]
    return "(no description)"


def merge_project(name: str, project_root: Path) -> dict:
    """Merge all docs for a project into one context file.

    Returns metadata dict for portfolio overview.
    """
    docs_dir = project_root / "docs"
    sections = []
    included_docs = []

    for doc_rel in DOC_ORDER:
        doc_path = docs_dir / doc_rel
        content = read_file(doc_path)
        if content:
            doc_name = Path(doc_rel).name
            sections.append(f"---\n## [DOCUMENT] {doc_name}\n\n{content}")
            included_docs.append(doc_name)

    if not sections:
        print(f"  ⚠ {name}: no docs found, skipping")
        return {}

    # Build merged file
    header = f"# PROJECT CONTEXT: {name}\n\n"
    header += f"> Auto-generated by gemini_context_sync.py | {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
    header += f"> Contains: {', '.join(included_docs)}\n"

    merged = header + "\n\n" + "\n\n".join(sections) + "\n"

    # Write output
    output_path = TARGET_DIR / f"{name}_CONTEXT.md"
    output_path.write_text(merged, encoding="utf-8")
    print(f"  ✅ {name}: {len(included_docs)} docs → {output_path.name}")

    # Extract metadata for overview
    soul_content = read_file(docs_dir / "PRODUCT_SOUL.md")
    one_liner = extract_one_liner(soul_content) if soul_content else "(no SOUL doc)"

    return {
        "name": name,
        "one_liner": one_liner,
        "docs": included_docs,
        "path": str(project_root),
    }


def generate_overview(project_metas: list[dict]):
    """Generate 00_PORTFOLIO_OVERVIEW.md with cross-project summary."""
    lines = [
        "# Portfolio Overview",
        "",
        f"> Auto-generated by gemini_context_sync.py | {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"> {len(project_metas)} projects in LittleTree ecosystem",
        "",
        "## Project Matrix",
        "",
        "| Project | Description | Docs |",
        "|---------|-------------|------|",
    ]

    for meta in project_metas:
        docs_str = ", ".join(d.replace(".md", "") for d in meta["docs"])
        lines.append(f"| **{meta['name']}** | {meta['one_liner']} | {docs_str} |")

    lines.append("")
    lines.append("## Quick Reference")
    lines.append("")
    for meta in project_metas:
        lines.append(f"- **{meta['name']}**: `{meta['path']}`")

    lines.append("")

    output_path = TARGET_DIR / "00_PORTFOLIO_OVERVIEW.md"
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  ✅ Portfolio overview → {output_path.name}")


def clean_old_outputs():
    """Remove previously generated files and sources/ directory."""
    count = 0
    for f in TARGET_DIR.glob("*_CONTEXT.md"):
        f.unlink()
        count += 1
    overview = TARGET_DIR / "00_PORTFOLIO_OVERVIEW.md"
    if overview.exists():
        overview.unlink()
        count += 1

    if count:
        print(f"  🧹 Cleaned {count} old generated files")


def main():
    print(f"Gemini Context Hub Sync")
    print(f"{'=' * 40}")

    # Step 1: Clean old generated files in current directory
    clean_old_outputs()

    # Step 2: Merge each project
    metas = []
    for name, root in PROJECTS.items():
        if not root.exists():
            print(f"  ⚠ {name}: project root not found ({root}), skipping")
            continue
        meta = merge_project(name, root)
        if meta:
            metas.append(meta)

    # Step 3: Generate overview
    if metas:
        generate_overview(metas)

    # Summary
    generated = list(TARGET_DIR.glob("*_CONTEXT.md"))
    if (TARGET_DIR / "00_PORTFOLIO_OVERVIEW.md").exists():
        generated.append(TARGET_DIR / "00_PORTFOLIO_OVERVIEW.md")
    total_files = len(generated)
    print(f"{'=' * 40}")
    print(f"Done! {total_files} files in {TARGET_DIR}")
    print(f"Gemini Gems slots: {total_files}/10 used, {10 - total_files} remaining")

    if total_files > 10:
        print(f"⚠ WARNING: {total_files} files exceed Gemini's 10-file limit!")
        sys.exit(1)


if __name__ == "__main__":
    main()
